### ISSUE TITLE
use this to capture mic audio to client browser

### ISSUE THREAD

**Issue by alisamir82** [ashishbajaj99/mic#11]
Hi, I am trying to create a tool that capture mic audio input - for this your node is doing a great job. however, the output is a .wav file, instead I would like to make that available via localhost for remote client to access. Please let me know if I can use your code your code for this or I will face some known limitation ? - I am new to this so please bear with me.
Thanks for your help.

**Comment by ashishbajaj99** [comment]
You mean you want to store it in a file that a client could access via
FTP/HTTP, etc.? Then the wav file that is generated can be stored at a
location where the FTP/HTTP server can access the file and serve it based
on client request.

OR

Do you mean you want to stream the data to connected clients? For this you
can use var micInputStream = micInstance.getAudioStream();
and treat it like any stream that can be fed to connected clients.

**Comment by ashishbajaj99** [comment]
See an example for #2 here:
https://github.com/ashishbajaj99/wake-on-voice-keyword/blob/master/index.js

**Comment by alisamir82** [comment]
Yes, I would like to implement that latter - ie feeding the stream to any connected client. 

I will follow the example, Many thanks for your help.

**Comment by alisamir82** [comment]
Would you please let me know if I can feed audio stream from mic to HTML5 audio tag
` micInputStream = micInstance.getAudioStream();`

Do you have an example for that by any change ? many thanks for your help.

**Comment by ashishbajaj99** [comment]
Sorry for the late reply, unfortunately I dont have an example for this. What you could do in the front end is to open a UDP socket and feed that to the HTML5 audio tag.

If you got this working, you could share an example here and I can include it into the repo as an example use case.
