### ISSUE TITLE
Write .wav file format with header.

### ISSUE THREAD

**Issue by VolodymyrTymets** [ashishbajaj99/mic#14]
I need make mathematical calculation with sound stream from microphone. For now it can be [fft](https://www.npmjs.com/package/ndarray-fft) transforming. I made this before with .wav file by decoding via [wav-decoder](https://www.npmjs.com/package/wav-decoder).

But when i try decode buffer from microphone as below, a have exeption `Invalid WAV file`.

```
micInputStream.on('data', function(data) {
   WavDecoder.decode(buffer);
});

```

Even, when i tried write wav file format then decode it. I also had exeption.

```
var micInputStream = micInstance.getAudioStream(); 
var outputFileStream = fs.WriteStream('output.wav'); 
micInputStream.pipe(outputFileStream);
micInstance.start();
```

I suppose, this because [raw](https://en.wikipedia.org/wiki/Raw_audio_format) format have no header.

So can i some way decode micInputStream data directly or write wav file format via mic?

**Comment by ashishbajaj99** [comment]
Yup the above is how I would do it as well. Thanks @nfriedly
