### ISSUE TITLE
WAV format generates slowed down audio files?

### ISSUE THREAD

**Issue by xavicolomer** [ashishbajaj99/mic#15]
Hi there!

I created a program that generates an audio file everytime there is a silence. Using standard configuration (raw) the files are creating correctly but if I try to generate .wav using the fileType, the first one is created correctly but the other files the speech sounds like the time is slowed down.

I know I can convert them using ffmpeg, but would be great to do it directly. There is a chance the script generating the files (fs.WriteStream) is wrong, but that would also mean raw files should be also broken

Any Idea?

**Comment by ashishbajaj99** [comment]
I would check the sampling rate settings...your playback sampling rate must match the recording sampling rate.
