### ISSUE TITLE
 Error: write after end

### ISSUE THREAD

**Issue by raghavSrih** [ashishbajaj99/mic#24]
Hi, 

When I edit your test code like below and run I get the error :  Error: write after end

``` 
micInputStream.on('stopComplete', function() {
    console.log("Got SIGNAL stopComplete");
    setTimeout(function() {
            micInstance.start();
    }, 5000);
}); 
```
Any idea how to fix/handle it ?

**Comment by ashishbajaj99** [comment]
On stop the process is killed using SIGTERM. If you can't to simply pause and resume after 5 seconds use the pause and resume framework rather than stop and start

**Comment by ginixsan** [comment]
You should create a function 'setUpMic' (or whatever) and then wrap constructor and everything inside that function and then call it again if you want to start and stop.
