### ISSUE TITLE
Can you provide an option to silence the prints inside IsSilence?

### ISSUE THREAD

**Issue by crunchex** [ashishbajaj99/mic#3]
I need to be able to quiet these prints: "Found speech block"

Great package... much more flexible and easy to use than some of the other microphone packages.

**Comment by ashishbajaj99** [comment]
Thanks @crunchex for the feedback. Am adding that in shortly.

**Comment by ashishbajaj99** [comment]
Done, check mic version 2.1.1

Cheers.
