### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by TuxSeb** [ashishbajaj99/mic#6]
Hi, i have an error when i try to launch your example ... 

 ```
$ node serveur.js
Got SIGNAL startComplete
Received Info: Capture WAVE 'stdin' : Signed 16 bit Little Endian, Fréquence 16000 Hz, Mono
arecord: set_params:1239: Nombre de canaux non disponible => Number of channels not available (translation) 
recording audioProcess has exited with code = 1
Got SIGNAL pauseComplete
Microphone paused
Got SIGNAL resumeComplete
Microphone resumed
Got SIGNAL stopComplete
Microhphone stopped

```
Can you help me please ?

Thanks you in advance !

**Comment by ashishbajaj99** [comment]
Looks like an issue with arecord inputs...that is causing arecord to fail.

Were you able to resolve it? Perhaps you can log the inputs that are going into arecord and try with tweaking them in the command line? Got to admit that I haven't tested this on linux in a while...so there could be a minor bug.

**Comment by ashishbajaj99** [comment]
Any updates? If not I will test it out on linux sometime in the future and look into it.

In case you have a fix, please submit a pull request. Much appreciated.

**Comment by ashishbajaj99** [comment]
@TuxSeb, I haven't heard back, so am closing the issue...

**Comment by TuxSeb** [comment]
i'm sorry, i was away

For the issue, i tried, i don't get the same error, but i got " Received Info: arecord: main:722: erreur à l'ouverture audio: Aucun fichier ou dossier de ce type", i tried on my desktop computer. 

Thanks for your patience.
