### ISSUE TITLE
Doesn't work for windows

### ISSUE THREAD

**Issue by leandrodvd** [ashishbajaj99/mic#8]
Itried to use this on windows and it doesn't work. It seems that 'rec' command doesn't exist in Sox for windows anymore. It seems that the following command must be used instead
sox -t waveaudio −d new-file.wav

**Comment by edmundo096** [comment]
Same issue.
Used similar solution of @leandrodvd inside mic.js

**Comment by ashishbajaj99** [comment]
Thanks guys, do you want to submit a pull request? I can merge it in...

**Comment by leandrodvd** [comment]
Hi, I Just created a pull request for this

**Comment by ashishbajaj99** [comment]
Sorry for the delay, its been merged now using #10 

Thank you very much for you PR.
